name: climbing_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.7
  http: ^1.2.1
  google_generative_ai: ^0.4.0
  google_fonts: ^6.1.0
  image_gallery_saver: ^2.0.3
  permission_handler: ^11.3.1
  universal_html: ^2.2.4

  table_calendar: ^3.1.2
  shared_preferences: ^2.2.3

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
